---
# tasks file for mkgin.vmware-harbor
# install with yum if...
    - name: add docker group
      group:
        name: docker
        state: present

    - name: Install docker-ce repo
      yum_repository: 
        name: 'docker-ce'
        description: 'Docker official repo'
        baseurl: https://mirrors.aliyun.com/docker-ce/linux/centos/7/$basearch/stable
        enabled: yes
        state: present
        gpgcheck: no

    - name: Remove old docker (prepare to install docker-ce) version if any
      package:
        name: "{{item}}"
        state: absent
      with_items:
        - docker
        - docker-common

    - name: Install docker engine
      package:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - docker-ce

    - name: Make sure docker service start
      service:
        name: docker
        state: started

    - name: Install docker-compose
      get_url:
          dest: /usr/local/bin/docker-compose
          url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
          mode: 0755

