---
- name: Check required variable is defined
  fail:
      msg: 'Failed as required variable is not defined'
  when: harbor_hostname is not defined or harbor_ssl_self_days is not defined or harbor_ssl_self_subject is not defined
- name: check or create ssl key dir
  file:
    state: directory
    path: "{{ harbor_install_dir }}/cert"

# maybe set up alternate names but let's not make it too complicated better to make certs
# with another role

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ harbor_cert_path }}"
    privatekey_path: "{{ harbor_cert_key_path }}"
    provider: selfsigned