---
# pre install dirs and paths
- include: harbor-data-directory.yml

- name: "harbor_install_skip_docker_compose compose ?"
  debug:
    var: harbor_install_skip_docker_compose
    verbosity: 2
# make sure we have docker and docker-compose
- include_tasks: install-docker-compose-{{ ansible_os_family }}.yml
- include: https_self_signed.yml
  when: not (harbor_ssl_cert is defined and harbor_ssl_cert_key is defined)
# otherwise we assume the certificate is there and ok if configured
- name: check or create ssl key dir
  file: 
    state: directory
    path: "{{harbor_cert_path|dirname}}"
- name: COPY customize certificates
  copy:
    src: "{{item[0]}}"
    dest: "{{item[1]}}" 
  with_list:
    - ['{{harbor_ssl_cert}}', '{{harbor_cert_path}}']
    - ["{{harbor_ssl_cert_key}}", '{{harbor_cert_key_path}}']
  when: harbor_ssl_cert is defined and harbor_ssl_cert_key is defined
# install harbor
- include: harbor-install.yml